// Datos mock iniciales del módulo Prospección Empresas.
//
// Construidos a partir de los nombres de empresas provistos (forestales,
// constructoras, telecom, climatización, fachadas/altura y alquiladoras) más un
// registro inicial de oportunidades de producto. Sirven como semilla mientras
// no exista persistencia real; cubren un abanico de etapas y semáforos.

import {
  emptyFleetProfile,
  emptyProviderProfile,
  type CompanyProspect,
  type ProductOpportunity,
} from "@/lib/models/prospeccion";

const SEED_CREATED = "2026-05-12";
const SEED_UPDATED = "2026-06-20";

/** Atajo para construir una oportunidad completando metadatos y bloques vacíos. */
function p(
  base: Omit<CompanyProspect, "creadoEn" | "actualizadoEn"> &
    Partial<Pick<CompanyProspect, "creadoEn" | "actualizadoEn">>,
): CompanyProspect {
  return {
    creadoEn: SEED_CREATED,
    actualizadoEn: SEED_UPDATED,
    ...base,
  };
}

export const mockProspects: CompanyProspect[] = [
  // ───────────────────────────── Forestales
  p({
    id: "prospect-upm-forestal-oriental",
    nombre: "UPM Forestal Oriental",
    rubro: "forestal",
    subrubro: "Producción forestal",
    tipoOrganizacion: "privada",
    localidad: "Fray Bentos",
    departamento: "Río Negro",
    web: "forestaloriental.com.uy",
    observaciones:
      "Operación forestal de gran escala. Flota propia importante para campo y logística.",
    fuente: "excel_contactos",
    etapa: "necesidades_relevadas",
    prioridad: "alta",
    contactos: [
      {
        id: "c-upm-1",
        nombre: "Gabriel Methol",
        cargo: "Jefe de mantenimiento de flota",
        area: "flota",
        telefono: "099 123 456",
        email: "gmethol@forestaloriental.com.uy",
        horarioRecomendado: "Mañana",
        esReferenteFinal: true,
        estado: "respondio",
      },
      {
        id: "c-upm-2",
        nombre: "Recepción operaciones",
        area: "administracion",
        telefono: "4562 0000",
        esDerivador: true,
        estado: "derivo",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "si",
      modeloMixto: "si",
      cantidadVehiculos: 60,
      tiposVehiculo: ["pickups", "camionetas", "camiones", "maquinaria"],
      marcasModelos: "Toyota Hilux, Ford Ranger, VW Amarok",
      usos: ["campo", "cuadrillas", "mantenimiento", "traslado de herramientas"],
      proximaRenovacion: "si",
      fechaEstimadaRenovacion: "2026-11-01",
      observaciones: "Renuevan por tramos cada año.",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "si",
      proveedorActual: "Proveedor regional de Paysandú",
      competidores: ["Accesorios del Litoral"],
      quienDecide: "Jefe de flota",
      quienUsa: "Cuadrillas de campo",
      oportunidadesEntrada: "Buscan estandarizar lonas y protectores de caja.",
    },
    necesidades: [
      {
        id: "n-upm-1",
        descripcion: "Lonas marítimas para Hilux",
        recomendadoPickup: "Lona enrollable + estructura",
        disponibilidad: "disponible",
      },
      {
        id: "n-upm-2",
        descripcion: "Soluciones de fijación de herramientas en caja",
        disponibilidad: "a_desarrollar",
        comentario: "Necesitan organizar herramientas pesadas.",
      },
    ],
    propuestas: [],
    actividades: [
      {
        id: "a-upm-1",
        tipo: "relevar_flota",
        fecha: "2026-06-02",
        responsable: "Daniel O.",
        estado: "realizada",
        resultadoObtenido: "Relevamiento de flota completo, 60 unidades.",
        contactoNombre: "Gabriel Methol",
      },
      {
        id: "a-upm-2",
        tipo: "enviar_propuesta",
        fecha: "2026-06-30",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Enviar propuesta de lonas + protectores.",
      },
    ],
    ultimoContacto: "2026-06-02",
  }),
  p({
    id: "prospect-montes-del-plata",
    nombre: "Montes del Plata",
    rubro: "forestal",
    subrubro: "Celulosa y forestación",
    tipoOrganizacion: "privada",
    localidad: "Conchillas",
    departamento: "Colonia",
    fuente: "excel_contactos",
    etapa: "referente_identificado",
    prioridad: "alta",
    contactos: [
      {
        id: "c-mdp-1",
        nombre: "Soledad Ramos",
        cargo: "Compras operativas",
        area: "compras",
        email: "compras@montesdelplata.com.uy",
        esReferenteFinal: true,
        estado: "contactado",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "si",
      modeloMixto: "si",
      cantidadVehiculos: 45,
      tiposVehiculo: ["pickups", "camionetas", "maquinaria"],
      usos: ["campo", "mantenimiento", "inspección"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile(), tieneProveedorActual: "no_se_sabe" },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-mdp-1",
        tipo: "reunion",
        fecha: "2026-07-08",
        hora: "10:00",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Relevar necesidades y proveedor actual.",
      },
    ],
    ultimoContacto: "2026-06-15",
  }),
  p({
    id: "prospect-grupo-forestal",
    nombre: "Grupo Forestal",
    rubro: "forestal",
    subrubro: "Servicios forestales",
    tipoOrganizacion: "contratista",
    localidad: "Tacuarembó",
    departamento: "Tacuarembó",
    fuente: "excel_contactos",
    etapa: "llamada_inicial_pendiente",
    prioridad: "media",
    contactos: [
      {
        id: "c-gf-1",
        nombre: "Sin referente aún",
        area: "otro",
        telefono: "063 22 000",
        estado: "no_contactado",
      },
    ],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-gf-1",
        tipo: "llamada",
        fecha: "2026-06-10",
        responsable: "Daniel O.",
        estado: "vencida",
        resultadoEsperado: "Identificar responsable de flota.",
      },
    ],
  }),
  p({
    id: "prospect-lumin",
    nombre: "Lumin",
    rubro: "forestal",
    subrubro: "Madera e industria",
    tipoOrganizacion: "privada",
    localidad: "Tacuarembó",
    departamento: "Tacuarembó",
    fuente: "excel_contactos",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),

  // ───────────────────────────── Constructoras
  p({
    id: "prospect-saceem",
    nombre: "Saceem",
    rubro: "constructora",
    subrubro: "Obra civil e infraestructura",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    web: "saceem.com",
    observaciones: "Constructora grande con obras en todo el país.",
    fuente: "excel_canales",
    etapa: "propuesta_enviada",
    prioridad: "alta",
    contactos: [
      {
        id: "c-sac-1",
        nombre: "Martín Pereira",
        cargo: "Gerente de equipos y flota",
        area: "flota",
        telefono: "2908 0000",
        whatsapp: "099 880 880",
        email: "mpereira@saceem.com",
        horarioRecomendado: "Tarde",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "no",
      modeloMixto: "no",
      cantidadVehiculos: 80,
      tiposVehiculo: ["pickups", "camionetas", "camiones", "utilitarios"],
      marcasModelos: "Toyota Hilux, Nissan Frontier",
      usos: ["obra", "traslado de herramientas", "cuadrillas"],
      proximaRenovacion: "si",
      fechaEstimadaRenovacion: "2026-09-15",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "si",
      proveedorActual: "Multimarca local",
      competidores: ["Accesorios MVD", "4x4 Center"],
      frecuenciaCompra: "Por obra nueva",
      quienDecide: "Gerencia de equipos",
      riesgosComerciales: "Tienen contrato anual con proveedor actual.",
      oportunidadesEntrada: "Renovación de flota en septiembre.",
    },
    necesidades: [
      {
        id: "n-sac-1",
        descripcion: "Protectores de caja y estribos",
        recomendadoPickup: "Kit protector + estribos",
        disponibilidad: "disponible",
      },
      {
        id: "n-sac-2",
        descripcion: "Racks para escaleras y andamios",
        disponibilidad: "no_disponible",
        comentario: "Piden solución de transporte de escaleras.",
      },
    ],
    propuestas: [
      {
        id: "prop-sac-1",
        fechaCreacion: "2026-06-05",
        estado: "enviada",
        version: 1,
        productos: ["Protectores de caja", "Estribos laterales", "Lonas"],
        montoEstimado: 12000,
        fechaEnvio: "2026-06-09",
        medioEnvio: "email",
        notas: "Propuesta inicial para 20 unidades nuevas.",
      },
    ],
    actividades: [
      {
        id: "a-sac-1",
        tipo: "validar_propuesta",
        fecha: "2026-06-27",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Confirmar recepción y agendar reunión.",
      },
    ],
    ultimoContacto: "2026-06-09",
  }),
  p({
    id: "prospect-stiler",
    nombre: "Stiler",
    rubro: "constructora",
    subrubro: "Construcción y desarrollos",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "presentacion_enviada",
    prioridad: "media",
    contactos: [
      {
        id: "c-sti-1",
        nombre: "Ana Methol",
        cargo: "Administración",
        area: "administracion",
        email: "admin@stiler.com.uy",
        esDerivador: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "no_se_sabe",
      cantidadVehiculos: 18,
      tiposVehiculo: ["pickups", "utilitarios"],
      usos: ["obra", "cuadrillas"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile(), tieneProveedorActual: "no_se_sabe" },
    necesidades: [
      {
        id: "n-sti-1",
        descripcion: "Lonas y barras",
        disponibilidad: "disponible",
      },
    ],
    propuestas: [
      {
        id: "prop-sti-1",
        fechaCreacion: "2026-06-12",
        estado: "no_iniciada",
        version: 1,
        productos: [],
      },
    ],
    actividades: [
      {
        id: "a-sti-1",
        tipo: "seguimiento",
        fecha: "2026-07-02",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Confirmar referente de flota.",
      },
    ],
    ultimoContacto: "2026-06-12",
  }),
  p({
    id: "prospect-teyma",
    nombre: "Teyma",
    rubro: "constructora",
    subrubro: "Infraestructura y energía",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "datos_basicos_relevados",
    prioridad: "media",
    contactos: [
      {
        id: "c-tey-1",
        nombre: "Pendiente de relevar",
        area: "flota",
        estado: "contactado",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "si",
      modeloMixto: "si",
      tiposVehiculo: ["pickups", "camionetas"],
      usos: ["obra", "mantenimiento"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-tey-1",
        tipo: "pedir_contacto",
        fecha: "2026-06-18",
        responsable: "Daniel O.",
        estado: "vencida",
        resultadoEsperado: "Conseguir referente de flota.",
      },
    ],
    ultimoContacto: "2026-06-04",
  }),
  p({
    id: "prospect-grinor",
    nombre: "Grinor",
    rubro: "constructora",
    subrubro: "Construcción",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),
  p({
    id: "prospect-campiglia",
    nombre: "Campiglia",
    rubro: "constructora",
    subrubro: "Construcción residencial",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "llamada_inicial_pendiente",
    prioridad: "media",
    contactos: [
      {
        id: "c-cam-1",
        nombre: "Mesa de entrada",
        area: "administracion",
        telefono: "2480 0000",
        estado: "no_contactado",
      },
    ],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-cam-1",
        tipo: "llamada",
        fecha: "2026-06-29",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Datos básicos y referente.",
      },
    ],
  }),
  p({
    id: "prospect-perez-noble",
    nombre: "Pérez Noble",
    rubro: "constructora",
    subrubro: "Construcción",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_contactos",
    etapa: "sin_oportunidad",
    prioridad: "baja",
    observaciones: "Por ahora terceriza toda la flota, sin decisión de compra.",
    contactos: [
      {
        id: "c-pn-1",
        nombre: "Carlos Pérez",
        area: "administracion",
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "no",
      flotaTercerizada: "si",
      proveedorFlotaActual: "Localiza",
    },
    proveedor: { ...emptyProviderProfile(), tieneProveedorActual: "no" },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),

  // ───────────────────────────── Telecomunicaciones
  p({
    id: "prospect-antel",
    nombre: "Antel",
    rubro: "telecomunicaciones",
    subrubro: "Telecom estatal",
    tipoOrganizacion: "estado",
    localidad: "Montevideo",
    departamento: "Montevideo",
    web: "antel.com.uy",
    observaciones:
      "Organismo estatal con flota grande para instalación y mantenimiento de fibra.",
    fuente: "excel_canales",
    etapa: "seguimiento_negociacion",
    prioridad: "alta",
    contactos: [
      {
        id: "c-ant-1",
        nombre: "Ing. Laura Sosa",
        cargo: "Jefa de logística de campo",
        area: "logistica",
        telefono: "2928 0000",
        email: "lsosa@antel.com.uy",
        horarioRecomendado: "Mañana",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "si",
      modeloMixto: "si",
      cantidadVehiculos: 120,
      tiposVehiculo: ["pickups", "camionetas", "vans", "utilitarios"],
      usos: ["fibra", "instalaciones", "traslado de escaleras", "cuadrillas"],
      proximaRenovacion: "si",
      fechaEstimadaRenovacion: "2026-12-01",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "si",
      proveedorActual: "Compra por licitación",
      competidores: ["Proveedores adjudicados en pliego"],
      quienDecide: "Compras públicas",
      riesgosComerciales: "Requiere proceso licitatorio.",
      oportunidadesEntrada: "Soluciones de transporte de escaleras y fibra.",
    },
    necesidades: [
      {
        id: "n-ant-1",
        descripcion: "Racks y soportes para escaleras",
        disponibilidad: "no_disponible",
        comentario: "Volumen alto: 120 vehículos.",
      },
      {
        id: "n-ant-2",
        descripcion: "Cajas organizadoras para herramientas y fibra",
        disponibilidad: "a_desarrollar",
      },
      {
        id: "n-ant-3",
        descripcion: "Lonas y protectores",
        disponibilidad: "disponible",
      },
    ],
    propuestas: [
      {
        id: "prop-ant-1",
        fechaCreacion: "2026-05-20",
        estado: "en_revision",
        version: 2,
        productos: ["Lonas", "Protectores", "Soportes de escalera (a cotizar)"],
        montoEstimado: 45000,
        fechaEnvio: "2026-05-28",
        medioEnvio: "email",
        notas: "Versión 2 ajustada a pliego.",
      },
    ],
    actividades: [
      {
        id: "a-ant-1",
        tipo: "seguimiento",
        fecha: "2026-06-26",
        hora: "09:30",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Conocer avance de evaluación interna.",
      },
    ],
    ultimoContacto: "2026-06-16",
  }),
  p({
    id: "prospect-tcc",
    nombre: "TCC",
    rubro: "telecomunicaciones",
    subrubro: "Cable / Internet",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "referente_identificado",
    prioridad: "media",
    contactos: [
      {
        id: "c-tcc-1",
        nombre: "Diego Lema",
        cargo: "Coordinador de instaladores",
        area: "servicios",
        whatsapp: "099 777 111",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "si",
      modeloMixto: "si",
      cantidadVehiculos: 35,
      tiposVehiculo: ["camionetas", "utilitarios"],
      usos: ["instalaciones", "traslado de escaleras", "cuadrillas"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile(), tieneProveedorActual: "no_se_sabe" },
    necesidades: [
      {
        id: "n-tcc-1",
        descripcion: "Soporte de escaleras en techo",
        disponibilidad: "no_disponible",
      },
    ],
    propuestas: [],
    actividades: [
      {
        id: "a-tcc-1",
        tipo: "relevar_flota",
        fecha: "2026-07-04",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Detallar vehículos y usos.",
      },
    ],
    ultimoContacto: "2026-06-14",
  }),
  p({
    id: "prospect-nuevo-siglo",
    nombre: "Nuevo Siglo",
    rubro: "telecomunicaciones",
    subrubro: "Cable / Internet",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),
  p({
    id: "prospect-montecable",
    nombre: "Montecable",
    rubro: "telecomunicaciones",
    subrubro: "Cable / Internet",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "llamada_inicial_pendiente",
    prioridad: "baja",
    contactos: [
      {
        id: "c-mc-1",
        nombre: "Mesa central",
        area: "administracion",
        telefono: "2200 0000",
        estado: "no_contactado",
      },
    ],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-mc-1",
        tipo: "llamada",
        fecha: "2026-07-10",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Datos básicos de flota.",
      },
    ],
  }),

  // ───────────────────────────── Climatización
  p({
    id: "prospect-dobarro-pichel",
    nombre: "Dobarro y Pichel",
    rubro: "climatizacion",
    subrubro: "Climatización industrial",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_contactos",
    etapa: "visita_coordinada",
    prioridad: "media",
    contactos: [
      {
        id: "c-dp-1",
        nombre: "Fernando Pichel",
        cargo: "Socio / operaciones",
        area: "servicios",
        telefono: "099 445 667",
        email: "fpichel@dyp.com.uy",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "no",
      cantidadVehiculos: 12,
      tiposVehiculo: ["camionetas", "utilitarios"],
      usos: ["traslado de herramientas", "instalaciones", "mantenimiento"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "no",
      competidores: [],
      oportunidadesEntrada: "Sin proveedor fijo, abren a propuestas.",
    },
    necesidades: [
      {
        id: "n-dp-1",
        descripcion: "Organización interna de herramientas",
        disponibilidad: "a_desarrollar",
      },
      {
        id: "n-dp-2",
        descripcion: "Lonas y estribos",
        disponibilidad: "disponible",
      },
    ],
    propuestas: [],
    actividades: [
      {
        id: "a-dp-1",
        tipo: "visita",
        fecha: "2026-06-25",
        hora: "15:00",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Ver vehículos y relevar necesidades en taller.",
      },
    ],
    ultimoContacto: "2026-06-18",
  }),
  p({
    id: "prospect-med-termico",
    nombre: "Med Acondicionamiento Térmico",
    rubro: "climatizacion",
    subrubro: "Climatización",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_contactos",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),
  p({
    id: "prospect-climatizacion-integral",
    nombre: "Climatización Integral",
    rubro: "climatizacion",
    subrubro: "Climatización",
    tipoOrganizacion: "privada",
    localidad: "Canelones",
    departamento: "Canelones",
    fuente: "excel_contactos",
    etapa: "datos_basicos_relevados",
    prioridad: "media",
    contactos: [
      {
        id: "c-ci-1",
        nombre: "Recepción",
        area: "administracion",
        estado: "contactado",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      cantidadVehiculos: 8,
      tiposVehiculo: ["camionetas"],
      usos: ["instalaciones", "mantenimiento"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-ci-1",
        tipo: "pedir_contacto",
        fecha: "2026-07-01",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Conseguir referente técnico.",
      },
    ],
    ultimoContacto: "2026-06-10",
  }),

  // ───────────────────────────── Fachadas / altura / seguridad
  p({
    id: "prospect-vertical",
    nombre: "Vertical",
    rubro: "fachadas_altura",
    subrubro: "Trabajos en altura",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    observaciones: "Trabajos en altura y limpieza de fachadas. Usan mucho equipo.",
    fuente: "excel_contactos",
    etapa: "necesidades_relevadas",
    prioridad: "alta",
    contactos: [
      {
        id: "c-ver-1",
        nombre: "Rodrigo Antúnez",
        cargo: "Jefe de cuadrillas",
        area: "servicios",
        whatsapp: "099 332 110",
        email: "rantunez@vertical.com.uy",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "no",
      cantidadVehiculos: 10,
      tiposVehiculo: ["camionetas", "pickups"],
      usos: ["traslado de escaleras", "líneas de vida", "cuadrillas", "herramientas"],
      proximaRenovacion: "no",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "no",
      oportunidadesEntrada: "Necesitan soluciones de transporte seguro de equipo.",
    },
    necesidades: [
      {
        id: "n-ver-1",
        descripcion: "Soporte para líneas de vida y escaleras",
        disponibilidad: "estrategica",
        comentario: "Producto no estándar, oportunidad de desarrollo.",
      },
      {
        id: "n-ver-2",
        descripcion: "Cajas porta-herramientas",
        disponibilidad: "no_disponible",
      },
    ],
    propuestas: [],
    actividades: [
      {
        id: "a-ver-1",
        tipo: "enviar_propuesta",
        fecha: "2026-07-03",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Cotizar soluciones de transporte de equipo.",
      },
    ],
    ultimoContacto: "2026-06-17",
  }),
  p({
    id: "prospect-linea-de-vida",
    nombre: "Línea de Vida",
    rubro: "fachadas_altura",
    subrubro: "Seguridad en altura",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_contactos",
    etapa: "llamada_inicial_pendiente",
    prioridad: "media",
    contactos: [
      {
        id: "c-lv-1",
        nombre: "Sin referente",
        area: "otro",
        estado: "no_respondio",
        intentosSinRespuesta: 2,
      },
    ],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-lv-1",
        tipo: "llamada",
        fecha: "2026-07-05",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Reintentar contacto.",
      },
    ],
  }),
  p({
    id: "prospect-pompier",
    nombre: "Seguridad Industrial Pompier",
    rubro: "fachadas_altura",
    subrubro: "Seguridad industrial",
    tipoOrganizacion: "privada",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_contactos",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),

  // ───────────────────────────── Alquiladoras / flotas tercerizadas
  p({
    id: "prospect-localiza",
    nombre: "Localiza",
    rubro: "alquiladora",
    subrubro: "Rent a car / flotas",
    tipoOrganizacion: "alquiladora",
    localidad: "Montevideo",
    departamento: "Montevideo",
    web: "localiza.com",
    observaciones:
      "Gran alquiladora con flota propia: posible cliente de accesorios en volumen.",
    fuente: "excel_canales",
    etapa: "referente_identificado",
    prioridad: "alta",
    contactos: [
      {
        id: "c-loc-1",
        nombre: "Valentina Cruz",
        cargo: "Gestión de flota",
        area: "flota",
        email: "vcruz@localiza.com",
        esReferenteFinal: true,
        estado: "respondio",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      flotaTercerizada: "no",
      cantidadVehiculos: 200,
      tiposVehiculo: ["pickups", "camionetas", "autos"],
      usos: ["alquiler", "flotas corporativas"],
      proximaRenovacion: "si",
      fechaEstimadaRenovacion: "2026-10-01",
    },
    proveedor: {
      ...emptyProviderProfile(),
      tieneProveedorActual: "si",
      proveedorActual: "Importador directo",
      competidores: ["Importadores de accesorios"],
      quienDecide: "Gestión de flota corporativa",
      oportunidadesEntrada: "Accesorios para segmento pickup de alquiler corporativo.",
    },
    necesidades: [
      {
        id: "n-loc-1",
        descripcion: "Lonas y protectores para pickups de alquiler",
        disponibilidad: "disponible",
      },
    ],
    propuestas: [],
    actividades: [
      {
        id: "a-loc-1",
        tipo: "reunion",
        fecha: "2026-07-09",
        hora: "11:00",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Presentar líneas de accesorios para flota de alquiler.",
      },
    ],
    ultimoContacto: "2026-06-19",
  }),
  p({
    id: "prospect-punta-car",
    nombre: "Punta Car",
    rubro: "alquiladora",
    subrubro: "Rent a car",
    tipoOrganizacion: "alquiladora",
    localidad: "Punta del Este",
    departamento: "Maldonado",
    fuente: "excel_canales",
    etapa: "datos_basicos_relevados",
    prioridad: "media",
    contactos: [
      {
        id: "c-pc-1",
        nombre: "Sucursal Maldonado",
        area: "administracion",
        telefono: "4244 0000",
        estado: "contactado",
      },
    ],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      cantidadVehiculos: 60,
      tiposVehiculo: ["autos", "camionetas", "pickups"],
      usos: ["alquiler"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-pc-1",
        tipo: "seguimiento",
        fecha: "2026-06-12",
        responsable: "Daniel O.",
        estado: "vencida",
        resultadoEsperado: "Conseguir referente de compras.",
      },
    ],
    ultimoContacto: "2026-05-30",
  }),
  p({
    id: "prospect-multicar",
    nombre: "Multicar",
    rubro: "alquiladora",
    subrubro: "Rent a car",
    tipoOrganizacion: "alquiladora",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "lead_detectado",
    prioridad: "baja",
    contactos: [],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [],
  }),
  p({
    id: "prospect-avis",
    nombre: "Avis",
    rubro: "alquiladora",
    subrubro: "Rent a car",
    tipoOrganizacion: "alquiladora",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "excel_canales",
    etapa: "llamada_inicial_pendiente",
    prioridad: "baja",
    contactos: [
      {
        id: "c-avis-1",
        nombre: "Central de reservas",
        area: "administracion",
        telefono: "2604 0000",
        estado: "no_contactado",
      },
    ],
    flota: { ...emptyFleetProfile() },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [],
    propuestas: [],
    actividades: [
      {
        id: "a-avis-1",
        tipo: "llamada",
        fecha: "2026-07-15",
        responsable: "Daniel O.",
        estado: "pendiente",
        resultadoEsperado: "Identificar área de flota.",
      },
    ],
  }),

  // ───────────────────────────── Estado uruguayo (sugerida)
  p({
    id: "prospect-intendencia-canelones",
    nombre: "Intendencia de Canelones",
    rubro: "estado",
    subrubro: "Gobierno departamental",
    tipoOrganizacion: "estado",
    localidad: "Canelones",
    departamento: "Canelones",
    observaciones:
      "Cuadrillas de vialidad, alumbrado e inspección. Flota grande de trabajo.",
    fuente: "sugerida",
    esSugerida: true,
    categoriaSugerida: "Empresas de vialidad",
    etapa: "lead_detectado",
    prioridad: "media",
    contactos: [],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      tiposVehiculo: ["pickups", "camionetas", "camiones", "maquinaria"],
      usos: ["vialidad", "alumbrado", "inspección", "cuadrillas"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [
      {
        id: "n-ica-1",
        descripcion: "Equipamiento para cuadrillas y herramientas",
        disponibilidad: "estrategica",
      },
    ],
    propuestas: [],
    actividades: [],
  }),
  p({
    id: "prospect-ute-contratistas",
    nombre: "Contratistas de UTE (alumbrado)",
    rubro: "estado",
    subrubro: "Contratistas de servicios públicos",
    tipoOrganizacion: "contratista",
    localidad: "Montevideo",
    departamento: "Montevideo",
    fuente: "sugerida",
    esSugerida: true,
    categoriaSugerida: "Contratistas de UTE / Antel / OSE",
    etapa: "lead_detectado",
    prioridad: "media",
    contactos: [],
    flota: {
      ...emptyFleetProfile(),
      flotaPropia: "si",
      tiposVehiculo: ["camionetas", "utilitarios"],
      usos: ["alumbrado", "traslado de escaleras", "cuadrillas"],
      proximaRenovacion: "no_se_sabe",
    },
    proveedor: { ...emptyProviderProfile() },
    necesidades: [
      {
        id: "n-ute-1",
        descripcion: "Soporte de escaleras y herramientas",
        disponibilidad: "no_disponible",
      },
    ],
    propuestas: [],
    actividades: [],
  }),
];

// ───────────────────────────── Registro inicial de oportunidades de producto

export const mockProductOpportunities: ProductOpportunity[] = [
  {
    id: "po-cargadores",
    producto: "Cargadores eléctricos para vehículos de flota",
    empresaSolicitante: "Varias (flotas)",
    menciones: 2,
    potencial: "medio",
    comentario: "Demanda creciente por electrificación de flotas.",
    estado: "evaluar",
  },
  {
    id: "po-escaleras",
    producto: "Soluciones de transporte de escaleras",
    rubro: "telecomunicaciones",
    empresaSolicitante: "Antel, TCC, contratistas",
    menciones: 4,
    potencial: "alto",
    comentario: "Recurrente en telecom y trabajos en altura.",
    estado: "desarrollar",
  },
  {
    id: "po-herramientas",
    producto: "Soluciones para organización de herramientas",
    rubro: "climatizacion",
    empresaSolicitante: "Dobarro y Pichel, Vertical",
    menciones: 3,
    potencial: "alto",
    comentario: "Cajas y racks internos para técnicos móviles.",
    estado: "buscar_proveedor",
  },
  {
    id: "po-lineas-vida",
    producto: "Soportes para líneas de vida en vehículos",
    rubro: "fachadas_altura",
    empresaSolicitante: "Vertical",
    menciones: 1,
    potencial: "medio",
    comentario: "Producto especializado para seguridad en altura.",
    estado: "idea",
  },
  {
    id: "po-cuadrillas",
    producto: "Equipamiento especial para cuadrillas",
    rubro: "estado",
    empresaSolicitante: "Intendencias, contratistas",
    menciones: 2,
    potencial: "medio",
    comentario: "Kits de organización para vehículos de cuadrilla.",
    estado: "evaluar",
  },
];
